#!/usr/bin/env python3
from pathlib import Path

root = Path(__file__).resolve().parents[1]
items = [
    ("Bounded fixture mission", "examples/fixture-mission.json", "schemas/mission.schema.json", "relay missions run examples/fixture-mission.json --fixture --json"),
    ("Provider-generated tools", "examples/provider-tools-mission.json", "schemas/tool-result-bundle.schema.json", "relay missions run examples/provider-tools-mission.json --json"),
    ("Transactional local index", "tests/relay_sqlite_store_smoke.sh", "docs/store-migration.md", "relay runs migrate-store --backend sqlite --confirm --json"),
    ("Retention preview", "tests/relay_retention_smoke.sh", "docs/retention-policy.md", "relay runs retention --keep-last 100 --json"),
    ("Enterprise boundary", "tests/relay_enterprise_smoke.sh", "schemas/signed-export.schema.json", "relay machine status --json"),
    ("Cursor-backed discovery", "tests/relay_discovery_cursor_smoke.sh", "src/runtime.kujo", "relay missions run mission.json --fixture --json"),
    ("Performance budgets", "benchmarks/budgets.json", "docs/performance.md", "bash scripts/benchmark_run_store.sh /tmp/relay-benchmark.json"),
    ("Exact-candidate release evidence", "docs/launch-checklist.md", "scripts/release_gate.sh", "bash scripts/release_gate.sh"),
]
lines = ["# Relay showcase gallery", "", "Every claim below resolves to committed evidence and a copyable command. Live,", "local-real, fixture, and blocked evidence retain their explicit labels.", "", "| Capability | Evidence | Contract or guide | Try it |", "| --- | --- | --- | --- |"]
for claim, evidence, contract, command in items:
    lines.append(f"| {claim} | [{evidence}](../{evidence}) | [{contract}](../{contract}) | `{command}` |")
lines += ["", "Generated by `scripts/generate_showcase_gallery.py`; edit the generator, then regenerate.", ""]
(root / "docs/showcase-gallery.md").write_text("\n".join(lines))
